WIP: Prepare unittest.
fkawa-play/retro-typing pull request #18
Opened 2018-01-29 12:30 UTC by tomoyuki-nakabayashi

### Overview
This relates with #3.
I prepared an unit test environment using googletest.

You can build and execute tests as follows:
```
cd unittests
cmake .
make
./unittests
```

### Changed contents
I set up CMake build scripts and made the first few tests.

### Impact of this change
The change never affects product code.

### Requirements for this change
Note that, I just built and executed the test only on Linux (Ubuntu 16.04).
I'm not sure the build script can work on other environment (e.g., Mac).
To build tests, CMake is additionally required (My CMake version is 3.5.1) .

### Supplement

2018-01-29 14:32 UTC, fkawa-play reviewed
Thanks for your patch.

2018-01-29 14:39 UTC, fkawa-play requested changes
Totally LGTM!!!  Could you add description for "how to test" into README.md ?

2018-01-29 14:40 UTC, fkawa-play approved these changes

2018-01-29 14:41 UTC, fkawa-play commented
Sorry.  I missed some operation.  Could you add description for "how to test" into README.md?

2018-01-30 11:24 UTC, tomoyuki-nakabayashi commented
Thanks for your quick response and review!
I added how to test into the file.
I found I forgot to commit gitignore of unit test, this affects only under unittests directory.
Please feel free to ask anything about test.
Basically, C language is not suitable for testing and sometime it requires a trick.

2018-02-10 12:32 UTC, tomoyuki-nakabayashi commented
Hi, have you checked my additional commit?  
I concern about you would miss it.  
thanks,

2018-02-15 03:55 UTC, fkawa-play commented
Sorry I was late reply....  Now I tried to test following environments.  As a result, I think it's OK to support testing on Ubuntu16.04 only.  In addition, please add following command for testing.

```
sudo apt install cmake
```

Here are operation logs:

* MacOS High Sierra 10.13.2
    * An error occurred while running 'make'

        ```
        error: invalid argument '-std=c++11' not allowed with 'C/ObjC'
        make[2]: *** [CMakeFiles/unittests.dir/Users/u4r/workspace/retro-typing/typing.c.o] Error 1
        make[1]: *** [CMakeFiles/unittests.dir/all] Error 2
        make: *** [all] Error 2
        ```
    * cmake --version

        ```
        cmake version 3.10.2
        ```
* Ubuntu16.04

    * cmake --version
        ```
        cmake version 3.5.1
        ```
    * It worked!  However, it's better to add  **sudo apt install cmake**  before 'cmake' in CUSTOMIZE.md

## Ubuntu16.04

* It's better to describe required packages 'cmake'.  Following error occurred in running 'cmake':

    ```
    The program 'cmake' is currently not installed. You can install it by typing:
    sudo apt install cmake
    ```

* run 'cmake .' after installed 'cmake':

    ```
    CMake Warning (dev) in CMakeLists.txt:
      No cmake_minimum_required command is present.  A line of code such as
     
    cmake_minimum_required(VERSION 3.5)
    
    should be added at the top of the file.  The version specified may be lower
    if you wish to support older CMake versions for this project.  For more
    information run "cmake --help-policy CMP0000".
    This warning is for project developers.  Use -Wno-dev to suppress it.

    -- Configuring done
    CMake Warning (dev) at CMakeLists.txt:42 (add_executable):
      Policy CMP0003 should be set before this line.  Add code such as

        if(COMMAND cmake_policy)
          cmake_policy(SET CMP0003 NEW)
        endif(COMMAND cmake_policy)

      as early as possible but after the most recent call to
      cmake_minimum_required or cmake_policy(VERSION).  This warning appears
      because target "unittests" links to some libraries for which the linker
      must search:
      
        ncursesw, tinfo

      and other libraries with known full path:

        /home/yushiro/retro-typing/unittests/googletest-build/googlemock/gtest/libgtest_main.a

      CMake is adding directories in the second list to the linker search path in
      case they are needed to find libraries from the first list (for backwards
      compatibility with CMake 2.4).  Set policy CMP0003 to OLD or NEW to enable
      or disable this behavior explicitly.  Run "cmake --help-policy CMP0003" for
      more information.
      This warning is for project developers.  Use -Wno-dev to suppress it.
      
    -- Generating done
    -- Build files have been written to: /home/yushiro/retro-typing/unittests
    ```
* Run 'make'

    ```
    ...(snip)...
    [ 88%] Building CXX object CMakeFiles/unittests.dir/typing_test.o
    [100%] Linking CXX executable unittests
    [100%] Built target unittests
    ```
* Run './unittests'

    ```
    Running main() from gtest_main.cc
    [==========] Running 3 tests from 1 test case.
    [----------] Global test environment set-up.
    [----------] 3 tests from TypingTest
    [ RUN      ] TypingTest.ExitFromRetroTyping
    Running main() from gtest_main.cc
    [       OK ] TypingTest.ExitFromRetroTyping (4 ms)
    [ RUN      ] TypingTest.CToI
    [       OK ] TypingTest.CToI (0 ms)
    [ RUN      ] TypingTest.GetComboMsgYeah
    [       OK ] TypingTest.GetComboMsgYeah (0 ms)
    [----------] 3 tests from TypingTest (4 ms total)
    
    [----------] Global test environment tear-down
    [==========] 3 tests from 1 test case ran. (4 ms total)
    [  PASSED  ] 3 tests.
    ```

2018-02-15 11:54 UTC, tomoyuki-nakabayashi commented
Thank you for your kind reply.

I guess you are using clang compiler not gcc on MacOS.
'-std=c++11' is a gcc specific compiler option, so you might encounter the error.

I replaced the gcc specific option to cmake property (CMAKE_CXX_STANDARD) that doesn't depend on target compiler.
I hope the modification makes you execute unit test on MacOS.

2018-02-15 12:26 UTC, fkawa-play commented
Thanks for your quick update.  I tested the latest patch and got an error.  Previously, I removed 'ncursesw' requirement in CMakeLists.txt.  I think it's OK not to support MacOS for testing at early stage :)  It may include some issues ...  In MacOS, make option is different.  It is not '-lncursesw' but '-lncurses'.

```
[100%] Built target googletest
-- Found PythonInterp: /usr/bin/python (found version "2.7.10")
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE
-- Found PkgConfig: /usr/local/bin/pkg-config (found version "0.29.2")
-- Checking for module 'ncursesw'
--   No package 'ncursesw' found
CMake Error at /usr/local/Cellar/cmake/3.10.2/share/cmake/Modules/FindPkgConfig.cmake:415 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.10.2/share/cmake/Modules/FindPkgConfig.cmake:593 (_pkg_check_modules_internal)
  CMakeLists.txt:45 (pkg_check_modules)


-- Configuring incomplete, errors occurred!
See also "/Users/u4r/workspace/retro-typing/unittests/CMakeFiles/CMakeOutput.log".
```

2018-02-16 11:06 UTC, tomoyuki-nakabayashi commented
>  I think it's OK not to support MacOS for testing at early stage :)

I agree with your decision.
I'll look into the problem near future.

BTW, I added description about test into CUSTOMIZE.md.

2018-02-17 10:57 UTC, fkawa-play commented
Hmm, new commands for testing didn't work correctly.  So, I just reverted one.

```
$ cd unittests/
$ mkdir build
$ cd build
$ cmake ..
-- Configuring done
-- Generating done
-- Build files have been written to: /home/yushiro/retro-typing/unittests/googletest-download
[ 11%] Performing update step for 'googletest'
From https://github.com/google/googletest
   4214050..3f0cf6b  master     -> origin/master
First, rewinding head to replay your work on top of it...
Fast-forwarded master to origin/master.
[ 22%] No configure step for 'googletest'
[ 33%] No build step for 'googletest'
[ 44%] No install step for 'googletest'
[ 55%] No test step for 'googletest'
[ 66%] Completed 'googletest'
[100%] Built target googletest
-- Configuring done
-- Generating done
-- Build files have been written to: /home/yushiro/retro-typing/unittests
$ make
make: *** No targets specified and no makefile found.  Stop.
$ ./unittests
-bash: ./unittests: No such file or directory
```

2018-02-17 11:05 UTC, merged

2018-02-17 11:05 UTC, fkawa-play commented
Thanks for your great patch!!

2018-02-17 13:01 UTC, tomoyuki-nakabayashi commented
Thanks, I'll add tests in my free time.